#include "bsp.h"
#include "sdk_errors.h"
#include "app_timer.h"
#include "nrf_log.h"
#include "nrf_log_ctrl.h"
#include "nrf_log_default_backends.h"

#include "ant.h"

/*

*/

/**@brief Function for handling events from the BSP module.
 *
 * @param[in]   event   Event generated by BSP.
 */
void bsp_event_handler(bsp_event_t event) {
    switch (event) {
        case BSP_EVENT_SLEEP:
            //nrf_pwr_mgmt_shutdown(NRF_PWR_MGMT_SHUTDOWN_GOTO_SYSOFF);
            break;

        default:
            break;
    }
}

void utils_setup(void) {
    ret_code_t err_code = NRF_LOG_INIT(NULL);
    APP_ERROR_CHECK(err_code);

    NRF_LOG_DEFAULT_BACKENDS_INIT();
    NRF_LOG_INFO("Logging setup complete");

    err_code = app_timer_init();
    APP_ERROR_CHECK(err_code);
    NRF_LOG_INFO("Timer Setup complete");

    err_code = bsp_init(0, bsp_event_handler);
    APP_ERROR_CHECK(err_code);
    NRF_LOG_INFO("BSP Setup complete");
}